// frontend/fx-admin-web/src/layouts/Header.vue
<template>
  <div class="header">
    <div class="left">
      <el-icon class="hamburger" @click="settingsStore.toggleSidebar"><Fold v-if="sidebarOpened" /><Expand v-else /></el-icon>
    </div>
    <div class="right">
      <el-dropdown>
        <span class="user-info"><el-avatar :size="30" /><span class="username">{{ userInfo?.nickname || 'Admin' }}</span></span>
        <template #dropdown>
          <el-dropdown-menu><el-dropdown-item @click="handleLogout">Logout</el-dropdown-item></el-dropdown-menu>
        </template>
      </el-dropdown>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import { Fold, Expand } from '@element-plus/icons-vue';
import { useSettingsStore } from '@/store/settings';
import { useUserStore } from '@/store/user';

const settingsStore = useSettingsStore();
const userStore = useUserStore();
const sidebarOpened = computed(() => settingsStore.sidebar.opened);
const userInfo = computed(() => userStore.userInfo);
const handleLogout = async () => { await userStore.logout(); };
</script>

<style scoped>
.header { height: 50px; display: flex; align-items: center; justify-content: space-between; padding: 0 16px; background: #fff; box-shadow: 0 1px 4px rgba(0,21,41,0.08); }
.left { display: flex; align-items: center; }
.hamburger { font-size: 20px; cursor: pointer; margin-right: 16px; }
.right { display: flex; align-items: center; }
.user-info { display: flex; align-items: center; cursor: pointer; }
.username { margin-left: 8px; }
</style>

// frontend/fx-trader-web/src/layouts/components/Header.tsx
import { Layout, Space, Avatar, Dropdown, Typography } from 'antd';
import { UserOutlined, SettingOutlined, LogoutOutlined } from '@ant-design/icons';
import { useUserStore } from '@/store/userStore';
import { useNavigate } from 'react-router-dom';

const { Header: AntHeader } = Layout;

export const Header = () => {
  const { userInfo, logout } = useUserStore();
  const navigate = useNavigate();
  const items = [
    {
      key: 'profile',
      icon: <UserOutlined />,
      label: 'Profile',
      onClick: () => navigate('/profile'),
    },
    { key: 'settings', icon: <SettingOutlined />, label: 'Settings' },
    { type: 'divider' as const },
    { key: 'logout', icon: <LogoutOutlined />, label: 'Logout', onClick: logout },
  ];
  return (
    <AntHeader
      style={{
        background: '#fff',
        padding: '0 24px',
        display: 'flex',
        justifyContent: 'flex-end',
        alignItems: 'center',
        borderBottom: '1px solid #f0f0f0',
      }}
    >
      <Dropdown menu={{ items }} placement="bottomRight">
        <Space style={{ cursor: 'pointer' }}>
          <Avatar icon={<UserOutlined />} />
          <Typography.Text>{userInfo?.nickname || 'User'}</Typography.Text>
        </Space>
      </Dropdown>
    </AntHeader>
  );
};
